@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String reg = "container-registry.oracle.com/olcne"
String version = "1.32"


String patch = "10"
String pause = "3.10"
String etcd = "3.5.25"
String coredns = "v1.13.2"
String flannel = "v0.27.4"
String ui_tag = "v0.35.0"
String ui_plugins = "v2.0.0"
String catalog = "v2.0.0"
String nginx = "1.26.3"

String base = "container-registry.oracle.com/olcne/ock:base-image"

def imgMacros = [
    "majorminor": version,
    "patch": patch,
    "pause": pause,
    "etcd": etcd,
    "coredns": coredns,
    "flannel": flannel,
    "ui_tag": ui_tag,
    "ui_plugins": ui_plugins,
    "catalog": catalog,
    "nginx": nginx,
    "base": base,
]

def containerDeps = [
    "${reg}/kube-apiserver:v${version}.${patch}",
    "${reg}/pause:${pause}",
    "${reg}/etcd:${etcd}",
    "${reg}/coredns:${coredns}",
    "${reg}/flannel:${flannel}",
    "${reg}/ui:${ui_tag}",
    "${reg}/ui-plugins:${ui_plugins}",
    "${reg}/ocne-catalog:${catalog}",
    "${reg}/nginx:${nginx}",
    base
]

olcnePipeline(
        branchPattern: new BranchPattern(master: "release/" + version, feature: '(?!^release/.*$)(^.*$)'),
        platforms: ['ol8'],
        architectures: ['x86_64', 'aarch64'],
        "macros": imgMacros,
        dependencies: [
                containers: containerDeps,
        ],
	preBuildCommands: [
		'export QA_RPATHS=1',
	],
)
